// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApqy-hJB2qvdvLk7Te8FIWyWrw5rnV_vc',
    appId: '1:932623245436:web:844bd92ec1a2a15aed69f9',
    messagingSenderId: '932623245436',
    projectId: 'authflutter-c5045',
    authDomain: 'authflutter-c5045.firebaseapp.com',
    storageBucket: 'authflutter-c5045.appspot.com',
    measurementId: 'G-6NH6501N9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-p8XLZiRPJwEdnqtPmuqIkcpmtyJuc0U',
    appId: '1:932623245436:android:6aa87e6b0e219a3eed69f9',
    messagingSenderId: '932623245436',
    projectId: 'authflutter-c5045',
    storageBucket: 'authflutter-c5045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu0VpDCP4AdzQPCkZMO6OML2nZv8hhuqA',
    appId: '1:932623245436:ios:74a1ebfbc7804429ed69f9',
    messagingSenderId: '932623245436',
    projectId: 'authflutter-c5045',
    storageBucket: 'authflutter-c5045.appspot.com',
    iosBundleId: 'com.example.googleAuthFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu0VpDCP4AdzQPCkZMO6OML2nZv8hhuqA',
    appId: '1:932623245436:ios:6785b29920d7cd3eed69f9',
    messagingSenderId: '932623245436',
    projectId: 'authflutter-c5045',
    storageBucket: 'authflutter-c5045.appspot.com',
    iosBundleId: 'com.example.googleAuthFlutter.RunnerTests',
  );
}
